### ISSUE TITLE
Add more details in case of issue while deciphering

### ISSUE THREAD

**Issue by TehBakker** [bolcom/spring-data-mongodb-encrypt#18]
Someone played with the DB and pushed unciphered data as an object in a field that was supposed to be ciphered.
When I tried to fetch this document I got an error, as expected.

The stacktrace looks like

_java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to [B
	at com.bol.secure.EncryptionEventListener$Decoder.apply(EncryptionEventListener.java:58)
	at com.bol.secure.EncryptionEventListener.cryptFields(EncryptionEventListener.java:134)
	at com.bol.secure.EncryptionEventListener.cryptFields(EncryptionEventListener.java:129)
	at com.bol.secure.EncryptionEventListener.cryptFields(EncryptionEventListener.java:127)
	at com.bol.secure.EncryptionEventListener.cryptFields(EncryptionEventListener.java:127)
	at com.bol.secure.EncryptionEventListener.cryptFields(EncryptionEventListener.java:127)
	at com.bol.secure.EncryptionEventListener.onAfterLoad(EncryptionEventListener.java:53)_

Kinda hard to find out where the error come from.

It would be great to add the ID of the mongo document and the field name that triggered this error.
It seems it would be fairly easy by passing the id of the parent object in EncryptionEventListener.cryptFields
The method is package limited though, so couldnt simply override it through a custom extention of EncryptionEventListener.

**Comment by agoston** [comment]
Hi,

Sorry for the late reply!

Great idea, I'll add wrapping exceptions in the `.onAfterLoad()` method so that these can be  reported or processed properly from  code.

**Comment by agoston** [comment]
Fixed in 2.2.
Please note that since this is a relatively deep change, I did not backport it into the spring-data v1 branch. If you feel like doing that, I'm happy to merge a pull request.
