### ISSUE TITLE
Non support Objects with fields like List<simple type>

### ISSUE THREAD

**Issue by ra-yura** [bolcom/spring-data-mongodb-encrypt#25]
My Object
public class ArbitrationConfig {
	@Id
	private String id;
	private `List<String>` test;
}

on save event I had:
Caused by: java.lang.IllegalArgumentException: Unknown reflective value class class java.lang.String
	at com.bol.secure.ReflectionEncryptionEventListener.diveIntoGeneric(ReflectionEncryptionEventListener.java:91)
	at com.bol.secure.ReflectionEncryptionEventListener.cryptFields(ReflectionEncryptionEventListener.java:53)
	at com.bol.secure.ReflectionEncryptionEventListener.onBeforeSave(ReflectionEncryptionEventListener.java:156)

**Comment by agoston** [comment]
Managed to reproduce this in test suite. Until a fix is released, please use the `CachedEncryptionEventListener`.

**Comment by agoston** [comment]
Fixed by 2.3.2
