### ISSUE TITLE
ClassCastException on decryption failures with custom id

### ISSUE THREAD

**Issue by ulfsauer0815** [bolcom/spring-data-mongodb-encrypt#31]
A `ClassCastException` is thrown when decryption fails on a document with an `_id` field type other than `ObjectId`.
The code tries to cast the field to `ObjectId` and throws a `ClassCastException` and not the expected `DocumentCryptException`, see here: https://github.com/bolcom/spring-data-mongodb-encrypt/blob/eacbba13683d9c62608151f91581f60633a72066/src/main/java/com/bol/secure/CachedEncryptionEventListener.java#L49-L54

The `_id` field may contain values of any BSON data type, other than an array, see mongodb docs: https://docs.mongodb.com/manual/core/document/#the-id-field

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.bson.types.ObjectId (java.lang.String is in module java.base of loader 'bootstrap'; org.bson.types.ObjectId is in unnamed module of loader 'app')
	at org.bson.Document.getObjectId(Document.java:248)
	at com.bol.secure.CachedEncryptionEventListener.onAfterLoad(CachedEncryptionEventListener.java:52)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:56)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:2361)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3159)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2799)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2532)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2515)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:876)
	at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:862)
	at com.bol.system.EncryptSystemTest.checkWrongKeyCustomId(EncryptSystemTest.java:449)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 40 more


```

**Comment by agoston** [comment]
Nice! Indeed, `_id` being of type `ObjectId` is a de-facto standard, not mandated by mongodb. 

It's actually quite lame that it fails on the error reporting.

I'll review your test & fixes and merge them as soon as I have the time. Thanks for drawing attention to this!

**Comment by ulfsauer0815** [comment]
Thanks for responding and reviewing so quickly! Awesome project! :)
