### ISSUE TITLE
BsonSerializationException when deserializing an encrypted field saved with Mongotemplate

### ISSUE THREAD

**Issue by vidibon2000ptz** [bolcom/spring-data-mongodb-encrypt#37]
So basically, I perform an update using MongoTemplate as such

```
        Update update = new Update();
        Binary binaryValue = new Binary(cryptVault.encrypt("thesolidrock".getBytes()));
        update.set("value", binaryValue);
        mongoTemplate.updateMulti(updateQuery, update, RecordFieldValue.class);
```

The field `value` is annotated with @Encrypted in RecordFieldValue.class

Now the challenge is that on decryption (using Spring Repository)
```
Optional<RecordFieldValue> rv = recordFieldValueRepository.findById("5f6c4f4f5603f57e3de1eb17");
```
where the id is the id of the field that was initially updated
It fails with the exception below:
```Caused by: com.bol.crypt.FieldCryptException: value
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:128)
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:80)
	at com.bol.secure.CachedEncryptionEventListener.onAfterLoad(CachedEncryptionEventListener.java:49)
	... 45 common frames omitted
Caused by: org.bson.BsonSerializationException: While decoding a BSON document 1 bytes were required, but only 0 remain
	at org.bson.io.ByteBufferBsonInput.ensureAvailable(ByteBufferBsonInput.java:218)
	at org.bson.io.ByteBufferBsonInput.readByte(ByteBufferBsonInput.java:71)
	at org.bson.io.ByteBufferBsonInput.readUntilNullByte(ByteBufferBsonInput.java:166)
	at org.bson.io.ByteBufferBsonInput.readCString(ByteBufferBsonInput.java:135)
	at org.bson.BsonBinaryReader.readBsonType(BsonBinaryReader.java:94)
	at org.bson.AbstractBsonWriter.pipeDocument(AbstractBsonWriter.java:788)
	at org.bson.AbstractBsonWriter.pipe(AbstractBsonWriter.java:756)
	at org.bson.BasicBSONDecoder.decode(BasicBSONDecoder.java:48)
	at com.bol.secure.AbstractEncryptionEventListener$Decoder.apply(AbstractEncryptionEventListener.java:37)
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:126)
```

**Comment by agoston** [comment]
I see your line of thinking, but BSON serialization of a String is a lot more than just dumping the bytes. For one, it contains the length, the data type, etc...

What you did there was dumping the encrypted raw string in the place where BSON would expect a whole bunch of metadata first.

While your approach works for the Update and the Find, it would fail on the deserialization.

I presume you wanted to do mass update of many objects in one go. You are right that this library has no support for that at the moment, since that is not an operation on the Repository.

Actually, with a slight modification, I think we can add support for what you are looking for into this library.

Please check out `AbstractEncryptionEventListener.Encoder`. That is the class that dumps the java POJOs into a BSON structure and encrypts it into a bytestream. It's relatively straightforward. With a slight change, it could be exposed for your purposes.

What do you think?

**Comment by agoston** [comment]
Come think of it, this is a bad idea. `CryptVault.encrypt()` generates a random salt each time to circumvent bruteforce attacks.

If you encrypt a data once and write that to multiple documents, you expose your data to bruteforce attacks, unnoticed. Maybe in 5 years' time, it will be an easy prey as no one expects that the same salt was used in a mass update.

But, assuming you know what you are doing and are fine with reduced security, this is how to do it:

```java
    class Encoder extends BasicBSONEncoder implements Function<Object, Object> {
        public Object apply(Object o) {
            byte[] serialized = encode(new BasicBSONObject("", o));
            return new Binary(cryptVault.encrypt(serialized));
        }
    }
```

NB, `cryptVailt.encrypt()` can take the crypt key version too; if unspecified, it uses the default.
Next, you make a new instance of this and simply apply it on your data:

```java
byte[] result = (byte[]) new Encoder().apply(new Document("super secret string"));
```

Again, please note this is unsecure and really should be used in emergencies only.
