### ISSUE TITLE
Null pointer with UUID

### ISSUE THREAD

**Issue by paulomass1** [bolcom/spring-data-mongodb-encrypt#40]
Hello, 

First of all, thank you for this useful library.
I have just a little problem when i try to save this entity with an UUID:

```
@Data
@AllArgsConstructor
@Document(collection = "analysis_document")
public class AnalysisDocumentDataEntity {
    /**
     * Id of the document
     */
    @Id
    private UUID id;

    /**
     * Content of the document
     */
    @Field
    @Encrypted
    private byte[] data;
    
    /**
     * Size of the document
     */
    @Field
    private int size;
}
```

The error:

```
java.lang.IllegalArgumentException: fr.bpce.digital.rlc.model.AnalysisDocumentDataEntity.id
	at com.bol.reflection.ReflectionCache.lambda$reflectRecursive$0(ReflectionCache.java:66)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:684)
	at com.bol.reflection.ReflectionCache.reflectRecursive(ReflectionCache.java:35)
	at com.bol.secure.CachedEncryptionEventListener.node(CachedEncryptionEventListener.java:28)
	at com.bol.secure.CachedEncryptionEventListener.onBeforeSave(CachedEncryptionEventListener.java:52)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:89)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:2361)
	at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:1477)
	at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:1421)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy157.save(Unknown Source)
	at fr.bpce.digital.rlc.service.DownloadService.handle(DownloadService.java:74)
	at fr.bpce.digital.rlc.queue.engine.QueueEngine.startQueueListener(QueueEngine.java:122)
	at fr.bpce.digital.rlc.queue.engine.QueueEngine.lambda$new$0(QueueEngine.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: java.util.UUID.mostSigBits
	at com.bol.reflection.ReflectionCache.lambda$reflectRecursive$0(ReflectionCache.java:66)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:684)
	at com.bol.reflection.ReflectionCache.reflectRecursive(ReflectionCache.java:35)
	at com.bol.reflection.ReflectionCache.lambda$reflectRecursive$0(ReflectionCache.java:60)
	... 39 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.bol.reflection.ReflectionCache.reflectRecursive(ReflectionCache.java:30)
	at com.bol.reflection.ReflectionCache.lambda$reflectRecursive$0(ReflectionCache.java:60)
	... 43 common frames omitted
```

**Comment by agoston** [comment]
Thanks!
Fixed in 2.5.1.
