### ISSUE TITLE
Having issue where sometimes field is encrypted and other times not

### ISSUE THREAD

**Issue by SlapBassist** [bolcom/spring-data-mongodb-encrypt#44]
I'm not sure where else to post this, but I am using version 2.3.2 and I'm finding on the whole the library works fine, but occasionally the resulting JSON stored in Mongo has the string representation of what I'm trying to have encrypted instead of the encrypted value. So sometimes it encrypts the value, but on rare occasions it does not. When it does not encrypt it, I get an error when it tries to decrypt it:

`
java.lang.IllegalStateException: Got class java.lang.String, expected: Binary or byte[]
	at com.bol.secure.AbstractEncryptionEventListener$Decoder.apply(AbstractEncryptionEventListener.java:32) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:127) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:81) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:133) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:81) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:133) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:81) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptDocument(CachedEncryptionEventListener.java:133) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.cryptFields(CachedEncryptionEventListener.java:81) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
	at com.bol.secure.CachedEncryptionEventListener.onAfterLoad(CachedEncryptionEventListener.java:50) ~[spring-data-mongodb-encrypt-2.3.2.jar!/:na]
`

The error is pretty clear in that the value it's trying to decrypt is a string versus a binary / byte[] type. When looking at the underlying mongodb document I've noticed it's getting stored as a string. Again, this only happen on rare occasions, but it still happens.

**Comment by agoston** [comment]
This happened to me once too. Keep in mind that there are a number of operations that don't pass through this library, for example, `findAndModify()` and also direct mongo client accesses, e.g. via `mongoTemplate.getCollection()`. These bypass the 'normal' serialization/deserialization of spring-data and thus are not passing through this library, either.

I suspect you used either one of those at some point in your code that causes this behavior.

Can you confirm this?
