### ISSUE TITLE
LocalDateTime field causes IllegalArgumentException

### ISSUE THREAD

**Issue by mamunsrdr** [bolcom/spring-data-mongodb-encrypt#45]
Having a field which is either `LocalDate` or `LocalDateTime` and not annotated with `@Encrypted` is causing `java.lang.IllegalArgumentException` -> `ReflectionCache.java:66`
version: `2.5.0`

```
java.lang.IllegalArgumentException: com.something.project.creationDate
	at com.bol.reflection.ReflectionCache.lambda$reflectRecursive$0(ReflectionCache.java:66)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:684)
	at com.bol.reflection.ReflectionCache.reflectRecursive(ReflectionCache.java:35)
	at com.bol.secure.CachedEncryptionEventListener.node(CachedEncryptionEventListener.java:28)
	at com.bol.secure.CachedEncryptionEventListener.onBeforeSave(CachedEncryptionEventListener.java:52)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:89)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
```

**Comment by agoston** [comment]
Sorry, which version are you using?
